server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ql_boot_simple?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yourPassword
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: yourPassword

  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
